name: Deploy React Site with gh-pages

on:
  push:
    branches: [ main ]
    paths:
      - 'website-react/**'
      - '.github/workflows/deploy-react-gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./website-react
        run: npm install

      - name: Build
        working-directory: ./website-react
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website-react/build
          publish_branch: gh-pages 