name: Sync Documentation Content

on:
  # Runs when docs are updated
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'resources/**'
      - 'README.md'

  # Allows manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for content updates
        id: check_updates
        run: |
          echo "Checking for documentation updates that need to be reflected in the website..."
          # This workflow can be extended to update specific sections of the HTML files
          # based on changes in the documentation
          
          # For now, we'll create a summary of what changed
          if git diff --name-only HEAD~1 HEAD | grep -E "(docs/|resources/|README.md)"; then
            echo "updates_found=true" >> $GITHUB_OUTPUT
          else
            echo "updates_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Create update summary
        if: steps.check_updates.outputs.updates_found == 'true'
        run: |
          # Create a summary of documentation changes
          echo "# Documentation Updates" > update_summary.md
          echo "" >> update_summary.md
          echo "The following documentation files have been updated:" >> update_summary.md
          echo "" >> update_summary.md
          git diff --name-only HEAD~1 HEAD | grep -E "(docs/|resources/|README.md)" >> update_summary.md
          echo "" >> update_summary.md
          echo "Please review these changes and update the corresponding HTML pages in the website directory if needed." >> update_summary.md

      - name: Create PR with update notification
        if: steps.check_updates.outputs.updates_found == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: documentation updates notification'
          title: 'Documentation Updates - Website Review Needed'
          body: |
            Documentation has been updated in the repository. Please review the changes and update the corresponding HTML pages in the website directory if needed.
            
            ## Updated Files
            See the update_summary.md file for a list of changed documentation files.
            
            ## Action Required
            - Review the documentation changes
            - Update the corresponding HTML pages in the website directory
            - Ensure consistency between documentation and website content
          branch: docs-update-notification-${{ github.run_number }}
          delete-branch: true
          add-paths: |
            update_summary.md 